### ISSUE TITLE
Error in PyOpenGL for ExFractalDB Construction?

### ISSUE THREAD

**Issue by colum2131** [masora1030/CVPR2022-Pretrained-ViT-PyTorch#2]
Hello, thank you for the very clear explanation and code.
I followed the environment construction method you introduced but an error occurred in ExFractalDB Construction, probably exfractaldb_render/image_render/render.py.
I couldn't understand if it was a bug or if there was a mistake in the environment construction, so I sent an issue.

素晴らしい研究ありがとうございます。
こちらのコードを動かそうとしたところ、ExFractalDB Constructionのところでエラーが出てしまいデータセットが作れずにいます。
ただ環境構築自体は紹介された方法を用いており、また私がOpenGLに見識がなくバグを修正することができないため、バグの箇所をイシューを送りました。
お手数お掛けしますが、よろしくお願いいたします。

### ERROR
`glVertexAttribPointer` didn't work.

```
Traceback (most recent call last):
  File "image_render/render.py", line 216, in <module>
    main(args)
  File "image_render/render.py", line 83, in main
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 4*6, ctypes.c_void_p(0))
  File "src/latebind.pyx", line 51, in OpenGL_accelerate.latebind.Curry.__call__
  File "/home/usr/.pyenv/versions/anaconda3-2022.05/envs/cvpr2022_env/lib/python3.7/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 469, in glVertexAttribPointer
    contextdata.setValue( key, array )
  File "/home/usr/.pyenv/versions/anaconda3-2022.05/envs/cvpr2022_env/lib/python3.7/site-packages/OpenGL/contextdata.py", line 58, in setValue
    context = getContext( context )
  File "/home/usr/.pyenv/versions/anaconda3-2022.05/envs/cvpr2022_env/lib/python3.7/site-packages/OpenGL/contextdata.py", line 41, in getContext
    """Attempt to retrieve context when no valid context"""
OpenGL.error.Error: Attempt to retrieve context when no valid context
```

### My Environment

* OS: 20.04.1-Ubuntu
* Python: 3.7.0

I built the environment using the following method and the results are as follows.

> Please install packages with the following command. (use conda env)
> ```
> $ conda env create -f conda_requirements.yaml
> $ conda activate cvpr2022_env
> ```

```
aenum==2.2.6
anyio==3.6.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
attrs==22.1.0
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==5.0.1
braceexpand==0.1.7
certifi==2021.10.8
cffi==1.15.1
charset-normalizer==2.1.1
click==8.1.3
configparser==5.3.0
ctypes-callable==1.0.4
cycler==0.11.0
debugpy==1.6.3
decorator==5.1.1
defusedxml==0.7.1
docker-pycreds==0.4.0
entrypoints==0.4
fastjsonschema==2.16.2
fonttools==4.28.5
future==0.18.2
gitdb==4.0.9
GitPython==3.1.29
glfw==2.5.0
idna==3.4
importlib-metadata==5.0.0
importlib-resources==5.10.0
ipykernel==6.16.2
ipython==7.34.0
ipython-genutils==0.2.0
ipywidgets==8.0.2
jedi==0.18.1
Jinja2==3.1.2
jsonschema==4.17.0
jupyter-server==1.23.0
jupyter_client==7.4.4
jupyter_core==4.11.2
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.3
kiwisolver==1.3.2
MarkupSafe==2.1.1
matplotlib==3.5.1
matplotlib-inline==0.1.6
mistune==2.0.4
nbclassic==0.4.8
nbclient==0.7.0
nbconvert==7.2.3
nbformat==5.7.0
nest-asyncio==1.5.6
noise==1.2.2
notebook==6.5.2
notebook_shim==0.2.2
numpy==1.21.5
open3d==0.9.0.0
opencv-python==4.5.5.62
OpenEXR @ file:///home/conda/feedstock_root/build_artifacts/openexr-python_1662043871119/work
packaging==21.3
pandas==1.1.5
pandocfilters==1.5.0
parso==0.8.3
Pegl==0.2a1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.0.0
pkgutil_resolve_name==1.3.10
plydata==0.4.3
plyfile==0.7.4
prometheus-client==0.15.0
promise==2.3
prompt-toolkit==3.0.32
protobuf==3.20.0
psutil==5.9.4
ptyprocess==0.7.0
pycparser==2.21
PyGLM==2.5.7
Pygments==2.13.0
PyOpenGL==3.1.5
PyOpenGL-accelerate==3.1.5
pyparsing==3.0.6
pyrsistent==0.19.2
PySDL2==0.9.10
pysdl2-dll==2.0.18
python-dateutil==2.8.2
pytz==2021.3
PyYAML==6.0
pyzmq==24.0.1
requests==2.28.1
Send2Trash==1.8.0
sentry-sdk==1.10.1
shortuuid==1.0.9
six==1.16.0
smmap==5.0.0
sniffio==1.3.0
soupsieve==2.3.2.post1
subprocess32==3.5.4
terminado==0.17.0
timm==0.4.12
tinycss2==1.2.1
torch==1.6.0
torchvision==0.7.0
tornado==6.2
tqdm==4.62.3
traitlets==5.5.0
typing_extensions==4.4.0
urllib3==1.26.12
wandb==0.10.12
watchdog==2.1.9
wcwidth==0.2.5
webdataset==0.1.62
webencodings==0.5.1
websocket-client==1.4.2
widgetsnbextension==4.0.3
zipp==3.10.0
```

**Comment by suzuryo3893** [comment]
@colum2131 Please try setting environment variable `PYOPENGL_PLATFORM=egl` to your terminal before executing EFDB generation.

**Comment by colum2131** [comment]
@suzuryo3893 I tried settind `PYOPENGL_PLATFORM=egl` and `os.environ['PYOPENGL_PLATFORM'] = 'egl'` in render.py, but the same error occurred.

**Comment by colum2131** [comment]
@suzuryo3893 Sorry, my code was mistaken.
I ran the command `PYOPENGL_PLATFORM=egl sh ExFractalDB_render.sh` and the EFDB images was successfully generated.
Thank you very much for answering my questions!
